DEFINE USER_NAME = &&1

SET SERVEROUTPUT ON

CREATE USER &USER_NAME IDENTIFIED BY oracle;
       /*DEFAULT TABLESPACE &TBS_NAME 
       TEMPORARY TABLESPACE temp
       QUOTA UNLIMITED ON &TBS_NAME;*/

SET SERVEROUTPUT OFF

UNDEFINE USER_NAME
