DEFINE USER_NAME = &&1

SET SERVEROUTPUT ON

INSERT INTO &&USER_NAME..product VALUES (1, 'Bitter Chocolate "Golden"', 100, 539, 360);
INSERT INTO &&USER_NAME..product VALUES (2, 'Milk Chocolate "Golden"', 100, 650, 360);
INSERT INTO &&USER_NAME..product VALUES (3, 'Sweets "Golden Ingots"', 300, 850, 240);

SET SERVEROUTPUT OFF

UNDEFINE USER_NAME
